// <auto-generated />
using System;
using EMIT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMIT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710193618_AjoutProfilEtudiant")]
    partial class AjoutProfilEtudiant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMIT.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<int>("Effectif")
                        .HasColumnType("integer");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("integer");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdNiveau");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("EMIT.Models.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCours"));

                    b.Property<bool>("DerogationExceptionnelle")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("integer");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalle")
                        .HasColumnType("integer");

                    b.Property<int>("Jour")
                        .HasColumnType("integer");

                    b.HasKey("IdCours");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdSalle");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("EMIT.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdMatiere");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("EMIT.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNiveau"));

                    b.Property<string>("NomNiveau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdNiveau");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("EMIT.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("EMIT.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("IdClasse")
                        .HasColumnType("integer");

                    b.Property<string>("Mention")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroInscription")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdClasse");

                    b.ToTable("Utilisateurs", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EMIT.Models.Enseignant", b =>
                {
                    b.HasBaseType("EMIT.Models.Utilisateur");

                    b.Property<int>("PlafondHeuresJournalieres")
                        .HasColumnType("integer");

                    b.ToTable("Enseignants", (string)null);
                });

            modelBuilder.Entity("EMIT.Models.Classe", b =>
                {
                    b.HasOne("EMIT.Models.Niveau", "Niveau")
                        .WithMany("Classes")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("EMIT.Models.Cours", b =>
                {
                    b.HasOne("EMIT.Models.Classe", "Classe")
                        .WithMany("Cours")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMIT.Models.Enseignant", "Enseignant")
                        .WithMany("Cours")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMIT.Models.Matiere", "Matiere")
                        .WithMany("Cours")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMIT.Models.Salle", "Salle")
                        .WithMany("Cours")
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EMIT.Models.Utilisateur", b =>
                {
                    b.HasOne("EMIT.Models.Classe", "Classe")
                        .WithMany("Etudiants")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("EMIT.Models.Enseignant", b =>
                {
                    b.HasOne("EMIT.Models.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("EMIT.Models.Enseignant", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMIT.Models.Classe", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("EMIT.Models.Matiere", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("EMIT.Models.Niveau", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("EMIT.Models.Salle", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("EMIT.Models.Enseignant", b =>
                {
                    b.Navigation("Cours");
                });
#pragma warning restore 612, 618
        }
    }
}
